/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffee_shop_management_system;

import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.text.DecimalFormat;
/**
 *
 * @author Dell
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        latte = new javax.swing.JLabel();
        Q1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        purchase1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        americano = new javax.swing.JLabel();
        Q7 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        purchase7 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cappuccino = new javax.swing.JLabel();
        Q4 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        purchase4 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        mocha = new javax.swing.JLabel();
        Q8 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        purchase8 = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        frappe = new javax.swing.JLabel();
        Q5 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        purchase5 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        macchiato = new javax.swing.JLabel();
        Q2 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        purchase2 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        espresso = new javax.swing.JLabel();
        Q3 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        purchase3 = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        cinnamon_roll = new javax.swing.JLabel();
        Q6 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        purchase6 = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        muffin = new javax.swing.JLabel();
        Q9 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        purchase9 = new javax.swing.JCheckBox();
        jLabel37 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        total_menu = new javax.swing.JButton();
        reset_menu = new javax.swing.JButton();
        exit_menu = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        total_amount_menu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cash_paid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        change = new javax.swing.JTextField();
        calculate_change = new javax.swing.JCheckBox();
        complete_order = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(101, 67, 33));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(207, 181, 149));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Symsical");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        login.setBackground(new java.awt.Color(207, 181, 149));
        login.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        login.setForeground(new java.awt.Color(101, 67, 33));
        login.setText("Login Page");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );

        jPanel3.setBackground(new java.awt.Color(193, 154, 107));

        jPanel4.setBackground(new java.awt.Color(237, 205, 175));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        latte.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        latte.setForeground(new java.awt.Color(66, 13, 9));
        latte.setText("Latte ");
        latte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                latteMouseClicked(evt);
            }
        });

        Q1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel4.setText("~ /600rs");

        purchase1.setText("Purchase");
        purchase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase1ActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/latte1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchase1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(latte, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(purchase1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latte)
                    .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 67, 33));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu ");

        jPanel5.setBackground(new java.awt.Color(237, 205, 175));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        americano.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        americano.setForeground(new java.awt.Color(66, 13, 9));
        americano.setText("Americano");
        americano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                americanoMouseClicked(evt);
            }
        });

        Q7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel7.setText("~ /600rs");

        purchase7.setText("Purchase");
        purchase7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase7ActionPerformed(evt);
            }
        });

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Americano.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchase7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(americano, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(Q7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(purchase7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(americano)
                    .addComponent(Q7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(237, 205, 175));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        cappuccino.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        cappuccino.setForeground(new java.awt.Color(66, 13, 9));
        cappuccino.setText("Cappuccino");
        cappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cappuccinoMouseClicked(evt);
            }
        });

        Q4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel13.setText("~ /600rs");

        purchase4.setText("Purchase");
        purchase4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase4ActionPerformed(evt);
            }
        });

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cappucino.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchase4))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(purchase4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cappuccino)
                    .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(237, 205, 175));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        mocha.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        mocha.setForeground(new java.awt.Color(66, 13, 9));
        mocha.setText("Mocha");
        mocha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mochaMouseClicked(evt);
            }
        });

        Q8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel16.setText("~ /650rs");

        purchase8.setText("Purchase");
        purchase8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase8ActionPerformed(evt);
            }
        });

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/moccha.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchase8))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(mocha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Q8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(purchase8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mocha)
                    .addComponent(Q8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(237, 205, 175));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        frappe.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        frappe.setForeground(new java.awt.Color(66, 13, 9));
        frappe.setText("Frappe");
        frappe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frappeMouseClicked(evt);
            }
        });

        Q5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel19.setText("~ /650rs");

        purchase5.setText("Purchase");
        purchase5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase5ActionPerformed(evt);
            }
        });

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/frappe.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchase5))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(frappe, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(purchase5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frappe)
                    .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(237, 205, 175));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        macchiato.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        macchiato.setForeground(new java.awt.Color(66, 13, 9));
        macchiato.setText("Macchiato");
        macchiato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                macchiatoMouseClicked(evt);
            }
        });

        Q2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel10.setText("~ /650rs");

        purchase2.setText("Purchase");
        purchase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase2ActionPerformed(evt);
            }
        });

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/macchiato.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchase2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(macchiato, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(purchase2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(macchiato)
                    .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(237, 205, 175));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        espresso.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        espresso.setForeground(new java.awt.Color(66, 13, 9));
        espresso.setText("Espresso");
        espresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espressoMouseClicked(evt);
            }
        });

        Q3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel22.setText("~ /700rs");

        purchase3.setText("Purchase");
        purchase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase3ActionPerformed(evt);
            }
        });

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/espresso.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchase3))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(espresso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(purchase3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espresso)
                    .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(237, 205, 175));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        cinnamon_roll.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        cinnamon_roll.setForeground(new java.awt.Color(66, 13, 9));
        cinnamon_roll.setText("Cinnamon Roll");
        cinnamon_roll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cinnamon_rollMouseClicked(evt);
            }
        });

        Q6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel25.setText("~ /700rs");

        purchase6.setText("Purchase");
        purchase6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase6ActionPerformed(evt);
            }
        });

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cinnamon roll.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cinnamon_roll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(purchase6))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(purchase6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinnamon_roll)
                    .addComponent(Q6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(237, 205, 175));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 67, 33)));

        muffin.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        muffin.setForeground(new java.awt.Color(66, 13, 9));
        muffin.setText("Muffin");
        muffin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muffinMouseClicked(evt);
            }
        });

        Q9.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel28.setText("~ /700rs");

        purchase9.setText("Purchase");
        purchase9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase9ActionPerformed(evt);
            }
        });

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/muffins.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase9)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(muffin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Q9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(purchase9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muffin)
                    .addComponent(Q9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(237, 205, 175));

        total_menu.setBackground(new java.awt.Color(101, 67, 33));
        total_menu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        total_menu.setForeground(new java.awt.Color(207, 181, 149));
        total_menu.setText("Total");
        total_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_menuActionPerformed(evt);
            }
        });

        reset_menu.setBackground(new java.awt.Color(101, 67, 33));
        reset_menu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        reset_menu.setForeground(new java.awt.Color(207, 181, 149));
        reset_menu.setText("Reset");
        reset_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_menuMouseClicked(evt);
            }
        });
        reset_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_menuActionPerformed(evt);
            }
        });

        exit_menu.setBackground(new java.awt.Color(101, 67, 33));
        exit_menu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        exit_menu.setForeground(new java.awt.Color(207, 181, 149));
        exit_menu.setText("Exit");
        exit_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(total_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(reset_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(758, 758, 758))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel14.setBackground(new java.awt.Color(101, 67, 33));

        receipt.setEditable(false);
        receipt.setBackground(new java.awt.Color(237, 205, 175));
        receipt.setColumns(20);
        receipt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        receipt.setForeground(new java.awt.Color(101, 67, 33));
        receipt.setRows(5);
        jScrollPane1.setViewportView(receipt);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(237, 205, 175));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total Amount");

        total_amount_menu.setEditable(false);
        total_amount_menu.setBackground(new java.awt.Color(237, 205, 175));
        total_amount_menu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_amount_menu.setForeground(new java.awt.Color(101, 67, 33));
        total_amount_menu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total_amount_menu.setText("0.0");
        total_amount_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_amount_menuActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(237, 205, 175));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cash Paid");

        cash_paid.setBackground(new java.awt.Color(237, 205, 175));
        cash_paid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cash_paid.setForeground(new java.awt.Color(101, 67, 33));
        cash_paid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cash_paid.setText("0.0");
        cash_paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash_paidActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(237, 205, 175));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Change");

        change.setEditable(false);
        change.setBackground(new java.awt.Color(237, 205, 175));
        change.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        change.setForeground(new java.awt.Color(101, 67, 33));
        change.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        change.setText("0.0");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        calculate_change.setBackground(new java.awt.Color(101, 67, 33));
        calculate_change.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        calculate_change.setForeground(new java.awt.Color(207, 181, 149));
        calculate_change.setText("Calculate Change");
        calculate_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_changeActionPerformed(evt);
            }
        });

        complete_order.setBackground(new java.awt.Color(207, 181, 149));
        complete_order.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        complete_order.setForeground(new java.awt.Color(101, 67, 33));
        complete_order.setText("Complete Order");
        complete_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_orderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cash_paid, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_amount_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calculate_change)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(complete_order, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_amount_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cash_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate_change))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(complete_order, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private double total = 0.0;
     private int cm = 0;
     private int cc = 0;
     private int cd =0;
     protected static int y;
           private int x=0;
           records r = new records();
           
     product_stock productStock = new product_stock();
           
   
        
    public void reset()
    {
        Q1.setValue(0);
        Q2.setValue(0);
        Q3.setValue(0);
        Q4.setValue(0);
        Q5.setValue(0);
        Q6.setValue(0);
        Q7.setValue(0);
        Q8.setValue(0);
        Q9.setValue(0);
        total_amount_menu.setText("0.0");
        cash_paid.setText("0.0");
        change.setText("0.0");
        receipt.setText(" ");
        purchase1.setSelected(false);
        purchase2.setSelected(false);
        purchase3.setSelected(false);
        purchase4.setSelected(false);
        purchase5.setSelected(false);
        purchase6.setSelected(false);
        purchase7.setSelected(false);
        purchase8.setSelected(false);
        purchase9.setSelected(false);
        calculate_change.setSelected(false);
        total = 0.0;
        x=0;
        cm = 0;
        cc = 0;
        cd =0;    }
    
    private void latteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_latteMouseClicked

     public void receipt_intro()
    {
        receipt.setText("*****************************************\n                Symsical\n                Receipt\n*****************************************"+
                "\nSerial no.\tItem name\tQuantity\tPrice\n");
    }
    
    private void purchase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase1ActionPerformed
        // TODO add your handling code here:
        int quantity = Integer.parseInt(Q1.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*600.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+latte.getText()+"\t"+Q1.getValue()+"\t"+price);
                purchase1.setSelected(false);
                Q1.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase1.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase1.setSelected(false);
            Q1.setValue(0);
        } 
    }//GEN-LAST:event_purchase1ActionPerformed

    private void americanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_americanoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_americanoMouseClicked

    private void purchase7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase7ActionPerformed
        // TODO add your handling code here:
         int quantity = Integer.parseInt(Q7.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*600.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+americano.getText()+"\t"+Q7.getValue()+"\t"+price);
                purchase7.setSelected(false);
                Q7.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase7.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase7.setSelected(false);
            Q7.setValue(0);
        }
    }//GEN-LAST:event_purchase7ActionPerformed

    private void cappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cappuccinoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cappuccinoMouseClicked

    private void purchase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase4ActionPerformed
        // TODO add your handling code here:
         int quantity = Integer.parseInt(Q4.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*600.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+cappuccino.getText()+"\t"+Q4.getValue()+"\t"+price);
                purchase4.setSelected(false);
                Q4.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase4.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase4.setSelected(false);
            Q4.setValue(0);
        }
    }//GEN-LAST:event_purchase4ActionPerformed

    private void mochaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mochaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mochaMouseClicked

    private void purchase8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase8ActionPerformed
        // TODO add your handling code here:
         int quantity = Integer.parseInt(Q8.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*650.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+mocha.getText()+"\t"+Q8.getValue()+"\t"+price);
                purchase8.setSelected(false);
                Q8.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase8.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase8.setSelected(false);
            Q8.setValue(0);
        }
    }//GEN-LAST:event_purchase8ActionPerformed

    private void frappeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frappeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_frappeMouseClicked

    private void purchase5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase5ActionPerformed
        // TODO add your handling code here:
         int quantity = Integer.parseInt(Q5.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*650.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+frappe.getText()+"\t"+Q5.getValue()+"\t"+price);
                purchase5.setSelected(false);
                Q5.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase5.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase5.setSelected(false);
            Q5.setValue(0);
        }
    }//GEN-LAST:event_purchase5ActionPerformed

    private void macchiatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_macchiatoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_macchiatoMouseClicked

    private void purchase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase2ActionPerformed
        // TODO add your handling code here:
        int quantity = Integer.parseInt(Q2.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*650.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+macchiato.getText()+"\t"+Q2.getValue()+"\t"+price);
                purchase2.setSelected(false);
                Q2.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase2.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase2.setSelected(false);
            Q2.setValue(0);
        }
    }//GEN-LAST:event_purchase2ActionPerformed

    private void espressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espressoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espressoMouseClicked

    private void purchase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase3ActionPerformed
        // TODO add your handling code here:
         int quantity = Integer.parseInt(Q3.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*700.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+espresso.getText()+"\t"+Q3.getValue()+"\t"+price);
                purchase3.setSelected(false);
                Q3.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase3.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase3.setSelected(false);
            Q3.setValue(0);
        }
    }//GEN-LAST:event_purchase3ActionPerformed

    private void cinnamon_rollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinnamon_rollMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cinnamon_rollMouseClicked

    private void purchase6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase6ActionPerformed
        // TODO add your handling code here:
         int quantity = Integer.parseInt(Q6.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*700.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+cinnamon_roll.getText()+"\t"+Q6.getValue()+"\t"+price);
                purchase6.setSelected(false);
                Q6.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase6.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase6.setSelected(false);
            Q6.setValue(0);
        }

    }//GEN-LAST:event_purchase6ActionPerformed

    private void muffinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muffinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_muffinMouseClicked

    private void purchase9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase9ActionPerformed
        // TODO add your handling code here:
         int quantity = Integer.parseInt(Q9.getValue().toString());
            if(quantity != 0)
        {
                x++;
                if(x==1)
                receipt_intro();
                double price = quantity*700.0;
                total+=price;
                receipt.setText(receipt.getText()+"\n"+x+". \t"+muffin.getText()+"\t"+Q9.getValue()+"\t"+price);
                purchase9.setSelected(false);
                Q9.setValue(0);
            }

      else if(quantity == 0)
            {
                JOptionPane.showMessageDialog(null,"Increase Item Quantity To Purchase The Product.");
                purchase9.setSelected(false);
            }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Product not available in stock");
            purchase9.setSelected(false);
            Q9.setValue(0);
        }
    }//GEN-LAST:event_purchase9ActionPerformed

    private void total_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_menuActionPerformed
        // TODO add your handling code here:
        if(total == 0.0)
        {
            JOptionPane.showMessageDialog(null, "Add Products First.");
        }
        else
        {  cm++;
            total_amount_menu.setText(Double.toString(total));
            receipt.setText(receipt.getText()+"\n*****************************************\n"+
                "Total Bill: "+total_amount_menu.getText()+
                "\n*****************************************");
        }
        
    }//GEN-LAST:event_total_menuActionPerformed

    private void reset_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_menuActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_reset_menuActionPerformed

    private void exit_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_menuActionPerformed

    private void reset_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_menuMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_reset_menuMouseClicked

    private void cash_paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_paidActionPerformed
        // TODO add your handling code here:
        cash_paid.getText();
    }//GEN-LAST:event_cash_paidActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeActionPerformed

    private void calculate_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_changeActionPerformed
        // TODO add your handling code here:
         double cp = Double.parseDouble(cash_paid.getText()); //cp = cash paid
        double tm = Double.parseDouble(total_amount_menu.getText());
        double ch; //ch = change
        
        if (cp<tm)
        {
            JOptionPane.showMessageDialog(null,"Insufficient Balance or No Cash Entered.");
            calculate_change.setSelected(false);
        }
        
        else if(cm == 0)
        {
            JOptionPane.showMessageDialog(null,"Process The Total First.");
            calculate_change.setSelected(false);
          
        }
        
        else
        {
            ch = cp-tm;
            DecimalFormat df = new DecimalFormat("00.00");
            String chan = df.format(ch);
            change.setText(chan); 
             receipt.setText(receipt.getText()+
                "\nCash Paid: "+cash_paid.getText()+
                "\n*****************************************\n"+
                "Change: "+change.getText()+
                "\n*****************************************\n");
            cc++;
            cd++;
        }
        
    }//GEN-LAST:event_calculate_changeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code :
    }//GEN-LAST:event_loginActionPerformed

    private void complete_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_orderActionPerformed
        // TODO add your handling code here:
        if(cm == 0)
        {
            JOptionPane.showMessageDialog(null, "Process The Total First.");
        }
        else if(cc == 0)
        {
          JOptionPane.showMessageDialog(null, "Calculate Change First.");
        }
        else 
        {
            y++;
            try {
             FileWriter fw = new FileWriter("Orders.txt",true);
             BufferedWriter b = new BufferedWriter(fw);
             fw.write("\nOrder: "+y+"\n");
             fw.write(receipt.getText());
             b.close();
             fw.close();
           } 
            catch (Exception e) {
             e.printStackTrace();
            } 
            reset();
        }
    }//GEN-LAST:event_complete_orderActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        login l = new login();
        try{
             l.setVisible(true);
            l.pack();
            this.dispose();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_loginMouseClicked

    private void total_amount_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_amount_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_amount_menuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Q1;
    private javax.swing.JSpinner Q2;
    private javax.swing.JSpinner Q3;
    private javax.swing.JSpinner Q4;
    private javax.swing.JSpinner Q5;
    private javax.swing.JSpinner Q6;
    private javax.swing.JSpinner Q7;
    private javax.swing.JSpinner Q8;
    private javax.swing.JSpinner Q9;
    private javax.swing.JLabel americano;
    private javax.swing.JCheckBox calculate_change;
    private javax.swing.JLabel cappuccino;
    private javax.swing.JTextField cash_paid;
    private javax.swing.JTextField change;
    private javax.swing.JLabel cinnamon_roll;
    private javax.swing.JButton complete_order;
    private javax.swing.JLabel espresso;
    private javax.swing.JButton exit_menu;
    private javax.swing.JLabel frappe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel latte;
    private javax.swing.JButton login;
    private javax.swing.JLabel macchiato;
    private javax.swing.JLabel mocha;
    private javax.swing.JLabel muffin;
    private javax.swing.JCheckBox purchase1;
    private javax.swing.JCheckBox purchase2;
    private javax.swing.JCheckBox purchase3;
    private javax.swing.JCheckBox purchase4;
    private javax.swing.JCheckBox purchase5;
    private javax.swing.JCheckBox purchase6;
    private javax.swing.JCheckBox purchase7;
    private javax.swing.JCheckBox purchase8;
    private javax.swing.JCheckBox purchase9;
    private javax.swing.JTextArea receipt;
    private javax.swing.JButton reset_menu;
    private javax.swing.JTextField total_amount_menu;
    private javax.swing.JButton total_menu;
    // End of variables declaration//GEN-END:variables
}
